-- AlterTable
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "openingTime" TEXT NOT NULL DEFAULT '08:00';
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "closingTime" TEXT NOT NULL DEFAULT '22:00';
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "is24Hours" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "isVisible" BOOLEAN NOT NULL DEFAULT true;
