-- AlterTable
ALTER TABLE "Ticket" ALTER COLUMN "companyId" DROP NOT NULL;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "message" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "priority" TEXT;
