-- AlterTable
ALTER TABLE "DirectBooking" ADD COLUMN IF NOT EXISTS "seats" INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "HourlyBooking" ADD COLUMN IF NOT EXISTS "seats" INTEGER NOT NULL DEFAULT 1;
